version: "3"

x-postgres-environment:
  &postgres-variables
  POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
  POSTGRES_PORT: ${POSTGRES_PORT:-5432}
  POSTGRES_USER: ${POSTGRES_USER:-postgres}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
  POSTGRES_DB: ${POSTGRES_DB:-postgres}

services:
#  postgres:
#    image: library/postgres:13
#    container_name: postgres
#    restart: on-failure
#    environment:
#      <<: *postgres-variables
#    volumes:
#      - db-data:/var/lib/postgresql/data
#      - ./postgres/:/docker-entrypoint-initdb.d/
#    ports:
#      - "5432:5432"
#
#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
#      - PGADMIN_DEFAULT_PASSWORD=admin
#    ports:
#      - "5050:80"
#    depends_on:
#      - postgres

  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"

volumes:
  db-data: